# Site settings
title: Jason Huff
email: jsnhff@gmail.com
description: "Jason Huff is an LA-based design manager and web worker on a mission to support artists."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jason-huff.com" # the base hostname & protocol for your site
twitter_username: jsnhff
github_username:  jsnhff

# Build settings
markdown: kramdown

# Collections
collections:
    projects:
        output: true
        permalink: /projects/:title/
    updates:
        output: true

# Handling Reading
include:      ['_pages']
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Permalinks for blog posts
permalink: /writing/:title/

# This will require each of these plugins automatically.
plugins:
- jekyll-sitemap
