/* ---------------------------------------------------------------
   build.mjs — renders the bio and the record as static HTML.

   Jekyll cannot run ES modules, so this runs in Node and writes two
   includes that the Mission page pulls in. Both are generated: edit
   src/bio.data.js or src/lists.data.js and run `node _bio/build.mjs`.

   The bio is written out FULLY OPEN, with real <a href> tags. That is
   what a crawler and a reader without JavaScript get. In the browser,
   enhance() replaces it with the collapsed interactive version.
--------------------------------------------------------------- */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { renderStatic, TOTAL } from "./src/bio.js";
import { COLLECTIONS, ANTHOLOGIES, WRITING, PRESS, SCHOLARSHIP } from "./src/lists.data.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = p => path.join(here, "..", "_includes", p);

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const banner = src =>
  `<!-- Generated by _bio/build.mjs from _bio/src/${src}. Do not edit by hand;\n`
  + `     edit the source and re-run \`node _bio/build.mjs\`. -->\n`;

/* ---- 1. the bio ---------------------------------------------------- */

fs.writeFileSync(out("bio-static.html"), banner("bio.data.js") + renderStatic() + "\n");

/* ---- 2. the record ------------------------------------------------- */
/* Anything still carrying a TODO is held back rather than shipped with a
   hole in it. Whatever is dropped is named on the console, so a silent
   omission cannot pass for a complete list. */

const held = [];
const ready = (rows, label) => rows.filter(r => {
  const todo = Object.values(r).some(v => typeof v === "string" && /TODO/.test(v));
  if (todo) held.push(`${label}: ${r.title || r.name || r.outlet}`);
  return !todo;
});

const pill = (label, href) =>
  `<a class="pill" href="${href}"${href.startsWith("http") ? ' target="_blank" rel="noopener"' : ""}>`
  + esc(label) + `<span class="arw" aria-hidden="true">↗</span></a>`;

// A title reads at one size whether or not it has somewhere to go — the link
// is marked by an underline and an arrow, not by shrinking.
//
// It used to be a pill when linked and plain text otherwise, which inverted
// the emphasis: the pill sets 0.66em uppercase in the dim colour, so every
// entry that HAD a link whispered while every dead end shouted in full-size
// ink. A pill is also the wrong shape for a title — these run to a full
// sentence, and a stadium border round three wrapped lines is not a label.
const titled = (label, href) => href
  ? `<a class="rec-title rec-link" href="${href}"${href.startsWith("http") ? ' target="_blank" rel="noopener"' : ""}>`
    + esc(label) + `<span class="arw" aria-hidden="true">↗</span></a>`
  : `<span class="rec-title">${esc(label)}</span>`;

// A year only gets a line of its own when there is one. Collections carry no
// date, and an empty span would still hold the space open above the entry.
const item = (year, lead, tail) =>
  `    <li class="rec-item">`
  + (year ? `<span class="rec-year">${esc(year)}</span>` : "")
  + `<span class="rec-body">${lead}${tail ? `<span class="rec-note">${tail}</span>` : ""}</span>`
  + `</li>`;

const section = (id, head, rows) =>
  `  <section class="rec" id="${id}">\n`
  + `    <h2 class="rec-head">${esc(head)}</h2>\n`
  + `    <ul class="rec-list">\n${rows.join("\n")}\n    </ul>\n`
  + `  </section>`;

const parts = [
  section("collections", "Collections",
    ready(COLLECTIONS, "Collections").map(c => item("", titled(c.name, c.href), esc(c.note)))),

  section("anthologies", "Anthologies",
    ready(ANTHOLOGIES, "Anthologies").map(a => item(a.year, titled(a.title, a.href), esc(a.note)))),

  section("writing", "Writing",
    ready(WRITING, "Writing").map(w => item(w.year, titled(w.title, w.href),
      esc(w.outlet) + (w.note ? " &middot; " + esc(w.note) : "")))),

  section("press", "Press",
    ready(PRESS, "Press").map(p => item(p.year, titled(p.outlet, p.href),
      esc(p.author) + (p.note ? " &middot; " + esc(p.note) : "")))),

  section("scholarship", "Scholarship",
    ready(SCHOLARSHIP, "Scholarship").map(s => item(s.year, titled(s.title, s.href),
      esc(s.author) + (s.venue ? " &middot; " + esc(s.venue) : "")))),
];

fs.writeFileSync(out("bio-lists.html"), banner("lists.data.js") + parts.join("\n\n") + "\n");

/* ---- 3. the browser's copy ------------------------------------------ */
/* The page imports these as modules at runtime. Copying them here means
   there is one source of truth: edit src/, run the build, and the static
   HTML and the interactive version cannot disagree. */

const runtime = path.join(here, "..", "js", "bio");
fs.mkdirSync(runtime, { recursive: true });
for (const f of ["bio.js", "bio.data.js", "glyphs.js"]) {
  fs.copyFileSync(path.join(here, "src", f), path.join(runtime, f));
}

/* ---- 4. say what happened ------------------------------------------ */

const links = (renderStatic().match(/<a class="pill"/g) || []).length;
console.log(`bio-static.html  ${TOTAL} chips expanded, ${links} links`);
console.log(`bio-lists.html   ${parts.length} sections`);
if (held.length) {
  console.log(`\nheld back for a TODO (${held.length}):`);
  held.forEach(h => console.log("  " + h));
}
