/* ---------------------------------------------------------------
   build.mjs — renders the bio and the record as static HTML.

   Jekyll cannot run ES modules, so this runs in Node and writes two
   includes that the Mission page pulls in. Both are generated: edit
   src/bio.data.js or src/lists.data.js and run `node _bio/build.mjs`.

   The bio is written out FULLY OPEN, with real <a href> tags. That is
   what a crawler and a reader without JavaScript get. In the browser,
   enhance() replaces it with the collapsed interactive version.
--------------------------------------------------------------- */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { renderStatic, TOTAL } from "./src/bio.js";
import { COLLECTIONS, ANTHOLOGIES, WRITING, PRESS, SCHOLARSHIP } from "./src/lists.data.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = p => path.join(here, "..", "_includes", p);

const esc = s => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const banner = src =>
  `<!-- Generated by _bio/build.mjs from _bio/src/${src}. Do not edit by hand;\n`
  + `     edit the source and re-run \`node _bio/build.mjs\`. -->\n`;

/* ---- 1. the bio ---------------------------------------------------- */

fs.writeFileSync(out("bio-static.html"), banner("bio.data.js") + renderStatic() + "\n");

/* ---- 2. the record ------------------------------------------------- */
/* Anything still carrying a TODO is held back rather than shipped with a
   hole in it. Whatever is dropped is named on the console, so a silent
   omission cannot pass for a complete list. */

const held = [];
const ready = (rows, label) => rows.filter(r => {
  const todo = Object.values(r).some(v => typeof v === "string" && /TODO/.test(v));
  if (todo) held.push(`${label}: ${r.title || r.name || r.outlet}`);
  return !todo;
});

const pill = (label, href) =>
  `<a class="pill" href="${href}"${href.startsWith("http") ? ' target="_blank" rel="noopener"' : ""}>`
  + esc(label) + `<span class="arw" aria-hidden="true">↗</span></a>`;

// A title reads at one size whether or not it has somewhere to go — the link
// is marked by an underline and an arrow, not by shrinking.
//
// It used to be a pill when linked and plain text otherwise, which inverted
// the emphasis: the pill sets 0.66em uppercase in the dim colour, so every
// entry that HAD a link whispered while every dead end shouted in full-size
// ink. A pill is also the wrong shape for a title — these run to a full
// sentence, and a stadium border round three wrapped lines is not a label.
const titled = (label, href) => href
  ? `<a class="rec-title rec-link" href="${href}"${href.startsWith("http") ? ' target="_blank" rel="noopener"' : ""}>`
    + esc(label) + `<span class="arw" aria-hidden="true">↗</span></a>`
  : `<span class="rec-title">${esc(label)}</span>`;

// A year only gets a line of its own when there is one. Collections carry no
// date, and an empty span would still hold the space open above the entry.
const item = (year, lead, tail) =>
  `    <li class="rec-item">`
  + (year ? `<span class="rec-year">${esc(year)}</span>` : "")
  + `<span class="rec-body">${lead}${tail ? `<span class="rec-note">${tail}</span>` : ""}</span>`
  + `</li>`;

const section = (id, head, rows) =>
  `  <section class="rec" id="${id}">\n`
  + `    <h2 class="rec-head">${esc(head)}</h2>\n`
  + `    <ul class="rec-list">\n${rows.join("\n")}\n    </ul>\n`
  + `  </section>`;

const parts = [
  section("collections", "Collections",
    ready(COLLECTIONS, "Collections").map(c => item("", titled(c.name, c.href), esc(c.note)))),

  section("anthologies", "Anthologies",
    ready(ANTHOLOGIES, "Anthologies").map(a => item(a.year, titled(a.title, a.href), esc(a.note)))),

  section("writing", "Writing",
    ready(WRITING, "Writing").map(w => item(w.year, titled(w.title, w.href),
      esc(w.outlet) + (w.note ? " &middot; " + esc(w.note) : "")))),

  section("press", "Press",
    ready(PRESS, "Press").map(p => item(p.year, titled(p.outlet, p.href),
      esc(p.author) + (p.note ? " &middot; " + esc(p.note) : "")))),

  section("scholarship", "Scholarship",
    ready(SCHOLARSHIP, "Scholarship").map(s => item(s.year, titled(s.title, s.href),
      esc(s.author) + (s.venue ? " &middot; " + esc(s.venue) : "")))),
];

fs.writeFileSync(out("bio-lists.html"), banner("lists.data.js") + parts.join("\n\n") + "\n");

/* ---- 3. what each work carries -------------------------------------- */
/* Liquid cannot read an ES module, so the record is inverted into a data
   file keyed by project slug. A project page then names its own holdings,
   anthologies, press and scholarship from the same source the record uses,
   rather than a second copy of the same facts drifting in front matter.

   Sections come out in this order and keep it — a work's credentials read
   the same way on every page. */

const SECTIONS = [
  // A collection's note glosses the record ("AutoSummarize and American
  // Psycho, acquired 2017…"), which on the AutoSummarize page just names the
  // work you are already looking at. The institution is the credential.
  ["Held in",      COLLECTIONS,  c => ({ name: c.name })],
  ["Published in", ANTHOLOGIES,  a => ({ name: a.title,  note: [a.year, a.note].filter(Boolean).join(". ") })],
  ["Press",        PRESS,        p => ({ name: p.outlet, note: [p.year, p.author].filter(Boolean).join(". ") })],
  ["Scholarship",  SCHOLARSHIP,  s => ({ name: s.title,  note: [s.year, s.author].filter(Boolean).join(". ") })],
];

// A `works` entry is either a slug or {slug, href}. The object form exists so
// an archive that gives every title its own page links to the right one; the
// bare form falls back to the record entry's single href.
const byWork = {};
for (const [head, rows, shape] of SECTIONS) {
  for (const row of rows) {
    for (const w of row.works || []) {
      const slug = typeof w === "string" ? w : w.slug;
      const href = (typeof w === "string" ? null : w.href) || row.href || null;
      const bucket = (byWork[slug] = byWork[slug] || {});
      (bucket[head] = bucket[head] || []).push({ ...shape(row), href });
    }
  }
}

const yaml = Object.entries(byWork).map(([slug, bucket]) =>
  `${slug}:\n` + SECTIONS.filter(([head]) => bucket[head]).map(([head]) =>
    `  - head: ${JSON.stringify(head)}\n    items:\n` + bucket[head].map(i =>
      `      - name: ${JSON.stringify(i.name)}\n`
      + (i.note ? `        note: ${JSON.stringify(i.note)}\n` : "")
      + (i.href ? `        href: ${JSON.stringify(i.href)}\n` : "")
    ).join("")
  ).join("")
).join("");

fs.mkdirSync(path.join(here, "..", "_data"), { recursive: true });
fs.writeFileSync(path.join(here, "..", "_data", "credits.yml"),
  `# Generated by _bio/build.mjs from _bio/src/lists.data.js. Do not edit by hand.\n${yaml}`);
fs.rmSync(path.join(here, "..", "_data", "collections.yml"), { force: true });

/* ---- 4. the browser's copy ------------------------------------------ */
/* The page imports these as modules at runtime. Copying them here means
   there is one source of truth: edit src/, run the build, and the static
   HTML and the interactive version cannot disagree. */

const runtime = path.join(here, "..", "js", "bio");
fs.mkdirSync(runtime, { recursive: true });
for (const f of ["bio.js", "bio.data.js", "glyphs.js"]) {
  fs.copyFileSync(path.join(here, "src", f), path.join(runtime, f));
}

/* ---- 5. say what happened ------------------------------------------ */

const links = (renderStatic().match(/<a class="pill"/g) || []).length;
console.log(`bio-static.html  ${TOTAL} chips expanded, ${links} links`);
console.log(`bio-lists.html   ${parts.length} sections`);
console.log(`credits.yml      ${Object.keys(byWork).length} works credentialed`);

// Anything in the record that names no work is listed, so a credit going
// unattached is a decision someone made rather than something that slipped.
const loose = SECTIONS.flatMap(([head, rows]) =>
  rows.filter(r => !(r.works || []).length).map(r => `${head}: ${r.title || r.name || r.outlet}`));
if (loose.length) {
  console.log(`\nnot tied to a work (${loose.length}):`);
  loose.forEach(l => console.log("  " + l));
}
if (held.length) {
  console.log(`\nheld back for a TODO (${held.length}):`);
  held.forEach(h => console.log("  " + h));
}
