/* ---------------------------------------------------------------
   linkcheck.mjs — tries every URL in the bio and the record, and
   writes LINK-CHECK.md.

   Run it anywhere with open egress:  node _bio/linkcheck.mjs

   Whatever it cannot reach it marks "?" rather than guessing. A "?"
   is not a pass — it means nobody has looked yet. The rule the list
   lives by: if a URL 404s, drop the href and keep the entry as plain
   text. An unlinked credential is fine; a dead link is not.
--------------------------------------------------------------- */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { DOC } from "./src/bio.data.js";
import { COLLECTIONS, ANTHOLOGIES, WRITING, PRESS, SCHOLARSHIP } from "./src/lists.data.js";

const here = path.dirname(fileURLToPath(import.meta.url));

/* ---- gather every URL, with the entry it belongs to ---------------- */

const urls = [];
const add = (section, label, href) => href && urls.push({ section, label, href });

// DOC is a list of paragraphs, each a list of nodes, and a chip's `add`
// holds more of the same — so recurse through arrays as well as chips.
(function walk(nodes) {
  for (const n of nodes) {
    if (typeof n === "string") continue;
    if (Array.isArray(n)) { walk(n); continue; }
    if (n.h) add("Bio", n.l, n.h);
    if (n.add) walk(n.add);
  }
})(DOC);

COLLECTIONS.forEach(c => add("Collections", c.name, c.href));
ANTHOLOGIES.forEach(a => add("Anthologies", `${a.year} ${a.title}`, a.href));
WRITING.forEach(w => add("Writing", `${w.year} ${w.title}`, w.href));
PRESS.forEach(p => add("Press", `${p.year} ${p.outlet} — ${p.note || ""}`, p.href));
SCHOLARSHIP.forEach(s => add("Scholarship", `${s.year || "n.d."} ${s.author} — ${s.title}`, s.href));

/* ---- try each one -------------------------------------------------- */
/* HEAD first because it is cheap; some hosts refuse it, so fall back to
   a GET. A redirect is followed and the landing URL reported — a link
   that ends up somewhere else is worth seeing even when it resolves. */

async function probe(href) {
  for (const method of ["HEAD", "GET"]) {
    try {
      const res = await fetch(href, {
        method, redirect: "follow",
        headers: { "user-agent": "Mozilla/5.0 (link check for jason-huff.com)" },
        signal: AbortSignal.timeout(20000),
      });
      if (method === "HEAD" && (res.status === 405 || res.status === 403)) continue;
      return { status: res.status, landed: res.url };
    } catch (err) {
      if (method === "GET") return { status: 0, err: err.message.slice(0, 60) };
    }
  }
  return { status: 0, err: "unreachable" };
}

const rows = [];
for (const u of urls) {
  const r = await probe(u.href);
  const moved = r.landed && r.landed.replace(/\/$/, "") !== u.href.replace(/\/$/, "");
  rows.push({ ...u, ...r, moved });
  process.stdout.write(`${String(r.status).padEnd(4)} ${u.href}\n`);
}

/* ---- classify ------------------------------------------------------- */
/* A 403 is not proof a link is broken — it is proof this machine was
   refused, and an egress proxy refuses everything with one. Only a 404
   or a 410 says the page is gone. Everything else is "unchecked", which
   is not a pass: it means nobody has looked yet.

   And if nearly every probe comes back identical, the network is the
   thing being measured, not the web. Say so instead of reporting a
   fictional pile of dead links — acting on that would strip working
   hrefs off entries that were fine. */

const counts = rows.reduce((m, r) => (m[r.status] = (m[r.status] || 0) + 1, m), {});
const [topStatus, topCount] = Object.entries(counts).sort((a, b) => b[1] - a[1])[0] || [];
const blanket = rows.length > 4 && topCount / rows.length > 0.8 && Number(topStatus) !== 200;

const mark = r => r.status === 0 ? "?" : r.status < 400 ? "ok" : String(r.status);
const dead = blanket ? [] : rows.filter(r => r.status === 404 || r.status === 410);
const unknown = blanket ? rows : rows.filter(r => r.status === 0 || (r.status >= 400 && r.status !== 404 && r.status !== 410));
const moved = rows.filter(r => r.moved && r.status < 400);

let md = `# Link check\n\n`
  + `Generated by \`node _bio/linkcheck.mjs\`. ${rows.length} URLs.\n\n`;

if (blanket) {
  md += `> **This run checked nothing.** ${topCount} of ${rows.length} probes came back\n`
     +  `> \`${topStatus}\`, which means the network refused this machine rather than\n`
     +  `> that the pages are gone. Every URL below is unverified. Re-run from a\n`
     +  `> connection with open egress before acting on any of it — and do not\n`
     +  `> strip hrefs on the strength of this file.\n\n`;
}

md += `- ok: ${rows.filter(r => r.status > 0 && r.status < 400).length}\n`
  + `- dead, 404/410 (drop the href, keep the entry as text): ${dead.length}\n`
  + `- redirected (resolves, but lands elsewhere): ${moved.length}\n`
  + `- unchecked (refused, blocked or timed out — NOT a pass): ${unknown.length}\n\n`;

if (dead.length) {
  md += `## Dead — fix these\n\n`;
  dead.forEach(r => { md += `- [ ] **${mark(r)}** ${r.section} · ${r.label}\n      ${r.href}\n`; });
  md += `\n`;
}
if (moved.length) {
  md += `## Redirected — consider updating to the landing URL\n\n`;
  moved.forEach(r => { md += `- [ ] ${r.section} · ${r.label}\n      ${r.href}\n      → ${r.landed}\n`; });
  md += `\n`;
}
if (unknown.length) {
  md += `## Unchecked — open by hand\n\n`;
  unknown.forEach(r => { md += `- [ ] ${r.section} · ${r.label}\n      ${r.href}\n`; });
  md += `\n`;
}

md += `## Everything, by section\n\n`;
for (const s of ["Bio", "Collections", "Anthologies", "Writing", "Press", "Scholarship"]) {
  const inSection = rows.filter(r => r.section === s);
  if (!inSection.length) continue;
  md += `### ${s}\n\n`;
  inSection.forEach(r => { md += `- \`${mark(r).padEnd(3)}\` ${r.label}\n      ${r.href}\n`; });
  md += `\n`;
}

fs.writeFileSync(path.join(here, "LINK-CHECK.md"), md);
console.log(blanket
  ? `\nwrote LINK-CHECK.md — CHECKED NOTHING: ${topCount}/${rows.length} probes returned ${topStatus}.\n  The network refused this machine. Re-run where egress is open.`
  : `\nwrote LINK-CHECK.md — ${dead.length} dead, ${moved.length} redirected, ${unknown.length} unchecked`);
